import json
import hashlib
import requests
from datetime import datetime

TARGETS = [
    {"id": "consumer", "url": "https://www.ag.state.mn.us/consumer/"},
    {"id": "data_requests", "url": "https://www.ag.state.mn.us/Data-Requests/"},
    {"id": "scams", "url": "https://www.ag.state.mn.us/consumer/scams/"},
    {"id": "press", "url": "https://www.ag.state.mn.us/Office/PressRelease/"},
]

DIFF_PATH = "site/diff.json"

def sha256(x):
    return hashlib.sha256(x.encode()).hexdigest()

def fetch(url):
    try:
        return requests.get(url, timeout=10).text
    except:
        return ""

def main():
    diff_rows = []

    # 🚨 ALWAYS SEED (no conditions, no ledger dependency)
    for t in TARGETS:
        body = fetch(t["url"])
        h = sha256(body)

        diff_rows.append({
            "receipt_id": f"BASELINE-{t['id']}",
            "source_url": t["url"],
            "prev_source_hash": None,
            "source_hash_sha256": h,
            "state": "seeded",
            "time": datetime.utcnow().isoformat() + "Z"
        })

    with open(DIFF_PATH, "w") as f:
        json.dump({
            "description": "diff.json is generated by Actions from ledger.jsonl",
            "schema": "array of {receipt_id, source_url, prev_source_hash, source_hash_sha256, state}",
            "data": diff_rows
        }, f, indent=2)

if __name__ == "__main__":
    main()
