import json
import hashlib
import requests
from datetime import datetime

TARGETS = [
    {"id": "consumer", "url": "https://www.ag.state.mn.us/consumer/"},
    {"id": "data_requests", "url": "https://www.ag.state.mn.us/Data-Requests/"},
    {"id": "scams", "url": "https://www.ag.state.mn.us/consumer/scams/"},
    {"id": "press", "url": "https://www.ag.state.mn.us/Office/PressRelease/"},
]

DIFF_PATH = "site/diff.json"

def sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()

def fetch(url: str) -> str:
    try:
        r = requests.get(url, timeout=10)
        return r.text
    except Exception:
        return ""

def main():
    rows = []
    now = datetime.utcnow().isoformat() + "Z"

    for t in TARGETS:
        body = fetch(t["url"])
        rows.append({
            "receipt_id": f"BASELINE-{t['id']}",
            "source_url": t["url"],
            "prev_source_hash": None,
            "source_hash_sha256": sha256(body),
            "state": "seeded",
            "time": now
        })

    with open(DIFF_PATH, "w", encoding="utf-8") as f:
        json.dump({
            "description": "diff.json is generated by Actions from monitored targets",
            "schema": "array of {receipt_id, source_url, prev_source_hash, source_hash_sha256, state, time}",
            "data": rows
        }, f, indent=2)

if __name__ == "__main__":
    main()
