import json
import hashlib
import requests
import os
import sys
from datetime import datetime, timezone

TARGETS = [
    {"id": "consumer", "url": "https://www.ag.state.mn.us/consumer/"},
    {"id": "data_requests", "url": "https://www.ag.state.mn.us/Data-Requests/"},
    {"id": "scams", "url": "https://www.ag.state.mn.us/consumer/scams/"},
    {"id": "communications", "url": "https://www.ag.state.mn.us/Office/Communications.asp"},
]

DIFF_PATH = "site/diff.json"
BASELINE_PATH = "site/baseline.json"


def sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def fetch(url: str) -> str:
    try:
        r = requests.get(url, timeout=10, headers={"User-Agent": "Mozilla/5.0"})
        r.raise_for_status()
        return r.text
    except Exception as e:
        print(f"FAIL: fetch error for {url}: {e}", file=sys.stderr)
        return None


def load_baseline() -> dict:
    if os.path.exists(BASELINE_PATH):
        with open(BASELINE_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}


def save_baseline(baseline: dict):
    os.makedirs(os.path.dirname(BASELINE_PATH), exist_ok=True)
    with open(BASELINE_PATH, "w", encoding="utf-8") as f:
        json.dump(baseline, f, indent=2)


def main():
    baseline = load_baseline()
    rows = []
    now = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")

    for t in TARGETS:
        body = fetch(t["url"])
        if body is None:
            print(f"FAIL: aborting run — fetch failed for {t['url']}", file=sys.stderr)
            sys.exit(1)

        current_hash = sha256(body)
        prev_hash = baseline.get(t["id"])

        if prev_hash is None:
            state = "seeded"
        elif current_hash == prev_hash:
            state = "unchanged"
        else:
            state = "changed"

        baseline[t["id"]] = current_hash

        rows.append({
            "receipt_id": f"BASELINE-{t['id']}" if state == "seeded" else f"DIFF-{t['id']}",
            "source_url": t["url"],
            "prev_source_hash": prev_hash,
            "source_hash_sha256": current_hash,
            "state": state,
            "time": now,
        })

    save_baseline(baseline)

    os.makedirs(os.path.dirname(DIFF_PATH), exist_ok=True)
    with open(DIFF_PATH, "w", encoding="utf-8") as f:
        json.dump({
            "description": "diff.json is generated by Actions from monitored targets",
            "schema": "array of {receipt_id, source_url, prev_source_hash, source_hash_sha256, state, time}",
            "generated_at": now,
            "data": rows,
        }, f, indent=2)

    changed = [r for r in rows if r["state"] == "changed"]
    print(f"diff complete: {len(rows)} targets, {len(changed)} changed")


if __name__ == "__main__":
    main()
